name: Static Code Analysis

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    name: Static Code Analysis
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        shell: bash
        run: |
          pip install --no-deps -r ./lock/requirements-dev.txt
          pip install --no-deps .

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch

      - name: ruff
        run: |
          ruff check --output-format=github .
          ruff format --check .

      - name: mypy
        run: |
          mypy .
